# Generated by Django 2.1.2 on 2018-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('v_mail', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=264)),
            ],
        ),
    ]
